"""集中保存全部前端临时数据，便于后续统一删除。"""

INTERVIEWS = [
    {
        "id": 1,
        "company_name": "网易",
        "position_name": "Java 后端开发工程师",
        "base_location": "杭州",
        "current_status": "待面试",
        "interview_time": "2026-10-08 14:00",
        "interview_end_time": "2026-10-08 15:00",
        "job_url": "https://example.com/jobs/netease-java",
        "updated_at": "2026-09-30 10:20",
    },
    {
        "id": 2,
        "company_name": "字节跳动",
        "position_name": "后端开发工程师",
        "base_location": "上海",
        "current_status": "笔试中",
        "interview_time": None,
        "interview_end_time": None,
        "job_url": "https://example.com/jobs/bytedance-backend",
        "updated_at": "2026-09-29 18:10",
    },
    {
        "id": 3,
        "company_name": "美团",
        "position_name": "Java 服务端开发",
        "base_location": "北京",
        "current_status": "已投递",
        "interview_time": None,
        "interview_end_time": None,
        "job_url": "https://example.com/jobs/meituan-java",
        "updated_at": "2026-09-27 09:30",
    },
    {
        "id": 4,
        "company_name": "携程",
        "position_name": "服务端研发工程师",
        "base_location": "上海",
        "current_status": "已结束",
        "interview_time": None,
        "interview_end_time": None,
        "job_url": "https://example.com/jobs/trip-backend",
        "updated_at": "2026-09-24 15:40",
    },
    {
        "id": 5,
        "company_name": "小红书",
        "position_name": "Java 研发工程师",
        "base_location": "上海",
        "current_status": "简历筛选中",
        "interview_time": None,
        "interview_end_time": None,
        "job_url": "https://example.com/jobs/xhs-java",
        "updated_at": "2026-09-30 08:50",
    },
    {
        "id": 6,
        "company_name": "腾讯",
        "position_name": "后台开发工程师",
        "base_location": "深圳",
        "current_status": "二面",
        "interview_time": "2026-10-09 16:00",
        "interview_end_time": "2026-10-09 17:00",
        "job_url": "https://example.com/jobs/tencent-backend",
        "updated_at": "2026-09-30 11:10",
    },
    {
        "id": 7,
        "company_name": "阿里巴巴",
        "position_name": "Java 研发工程师",
        "base_location": "杭州",
        "current_status": "三面",
        "interview_time": "2026-10-10 10:30",
        "interview_end_time": "2026-10-10 11:30",
        "job_url": "https://example.com/jobs/alibaba-java",
        "updated_at": "2026-09-30 11:30",
    },
    {
        "id": 8,
        "company_name": "百度",
        "position_name": "服务端研发工程师",
        "base_location": "北京",
        "current_status": "HR面",
        "interview_time": "2026-10-11 15:00",
        "interview_end_time": "2026-10-11 16:00",
        "job_url": "https://example.com/jobs/baidu-server",
        "updated_at": "2026-09-30 12:00",
    },
    {
        "id": 9,
        "company_name": "京东",
        "position_name": "Java 后端工程师",
        "base_location": "北京",
        "current_status": "Offer",
        "interview_time": None,
        "interview_end_time": None,
        "job_url": "https://example.com/jobs/jd-java",
        "updated_at": "2026-09-30 12:20",
    },
    {
        "id": 10,
        "company_name": "快手",
        "position_name": "基础架构研发工程师",
        "base_location": "北京",
        "current_status": "简历筛选中",
        "interview_time": None,
        "interview_end_time": None,
        "job_url": "https://example.com/jobs/kuaishou-infra",
        "updated_at": "2026-09-30 13:10",
    },
    {
        "id": 11,
        "company_name": "滴滴",
        "position_name": "Java 服务端开发工程师",
        "base_location": "北京",
        "current_status": "笔试中",
        "interview_time": None,
        "interview_end_time": None,
        "job_url": "https://example.com/jobs/didi-java",
        "updated_at": "2026-09-30 13:30",
    },
    {
        "id": 12,
        "company_name": "小米",
        "position_name": "后端开发工程师",
        "base_location": "北京",
        "current_status": "已结束",
        "interview_time": None,
        "interview_end_time": None,
        "job_url": "https://example.com/jobs/xiaomi-backend",
        "updated_at": "2026-09-30 13:50",
    },
]

JOB_RECOMMENDATIONS = [
    {
        "id": "job-001",
        "company_name": "哔哩哔哩",
        "position_name": "Java 后端开发工程师",
        "base_location": "上海",
        "work_experience": "应届生",
        "salary": "25-40K·16薪",
        "match_score": 92,
        "match_reasons": ["Java 服务端经验匹配", "熟悉 MySQL 与 Redis", "业务方向符合偏好"],
        "risk_points": ["要求有高并发项目经验"],
        "jd_summary": "负责内容平台核心服务的设计、开发和性能优化。",
        "job_description": "岗位职责：参与内容平台核心服务建设，负责服务治理、性能优化和稳定性建设。任职要求：熟悉 Java、Spring Boot、MySQL、Redis，理解分布式系统。",
        "job_url": "https://example.com/jobs/bilibili-java",
    },
    {
        "id": "job-002",
        "company_name": "得物 App",
        "position_name": "后端研发工程师",
        "base_location": "上海",
        "work_experience": "应届生",
        "salary": "25-45K·16薪",
        "match_score": 88,
        "match_reasons": ["技术栈高度匹配", "电商交易业务有成长空间"],
        "risk_points": ["可能涉及较多值班和稳定性工作"],
        "jd_summary": "负责交易链路、履约系统和基础服务开发。",
        "job_description": "岗位职责：负责交易与履约领域后端系统研发。任职要求：计算机相关专业，熟悉 Java 生态和关系型数据库。",
        "job_url": "https://example.com/jobs/dewu-backend",
    },
    {
        "id": "job-003",
        "company_name": "蚂蚁集团",
        "position_name": "Java 研发工程师",
        "base_location": "杭州",
        "work_experience": "应届生",
        "salary": "25-40K·16薪",
        "match_score": 84,
        "match_reasons": ["Java 基础匹配", "服务端研究背景匹配"],
        "risk_points": ["算法与系统设计要求较高", "竞争强度较大"],
        "jd_summary": "参与支付与数字金融基础平台研发。",
        "job_description": "岗位职责：参与金融级分布式系统建设。任职要求：扎实的数据结构、操作系统和网络基础，熟悉 Java。",
        "job_url": "https://example.com/jobs/ant-java",
    },
]

MOCK_INTERVIEW_QUESTIONS = [
    "请介绍一个你最熟悉的 Java 服务端项目，并说明你负责的核心模块。",
    "这个项目中最复杂的一次性能问题是什么？你如何定位并解决？",
    "如果接口流量突然增长十倍，你会从哪些层面设计保护方案？",
    "请解释 MySQL 索引失效的常见场景，并结合项目举例。",
    "你如何设计一个可恢复、可观测的 Agent 工具调用流程？",
]
